# Generated by Django 2.1 on 2018-08-09 21:59

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("spirits", "0001_initial"),
        ("world", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckIn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bottle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="spirits.Bottle"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("flavor_profiles", models.ManyToManyField(to="spirits.FlavorProfile")),
                (
                    "friends",
                    models.ManyToManyField(
                        related_name="friend_checkins", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="world.Location",
                    ),
                ),
            ],
        )
    ]
