# Generated by Django 2.1 on 2018-08-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cask", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="checkin",
            name="rating",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        )
    ]
