# Generated by Django 2.1 on 2018-08-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("spirits", "0002_auto_20180809_2239")]

    operations = [
        migrations.AlterField(
            model_name="bottle",
            name="name",
            field=models.CharField(max_length=128, unique=True),
        )
    ]
